/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "RPCDICE.h"

bool_t
xdr_inputData (XDR *xdrs, inputData *objp)
{
	register int32_t *buf;


	if (xdrs->x_op == XDR_ENCODE) {
		buf = XDR_INLINE (xdrs, 4 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_int (xdrs, &objp->numOfRolls))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->threshold))
				 return FALSE;
			 if (!xdr_bool (xdrs, &objp->hasRerollAtOne))
				 return FALSE;
			 if (!xdr_bool (xdrs, &objp->hasFullReroll))
				 return FALSE;
		} else {
			IXDR_PUT_LONG(buf, objp->numOfRolls);
			IXDR_PUT_LONG(buf, objp->threshold);
			IXDR_PUT_BOOL(buf, objp->hasRerollAtOne);
			IXDR_PUT_BOOL(buf, objp->hasFullReroll);
		}
		return TRUE;
	} else if (xdrs->x_op == XDR_DECODE) {
		buf = XDR_INLINE (xdrs, 4 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_int (xdrs, &objp->numOfRolls))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->threshold))
				 return FALSE;
			 if (!xdr_bool (xdrs, &objp->hasRerollAtOne))
				 return FALSE;
			 if (!xdr_bool (xdrs, &objp->hasFullReroll))
				 return FALSE;
		} else {
			objp->numOfRolls = IXDR_GET_LONG(buf);
			objp->threshold = IXDR_GET_LONG(buf);
			objp->hasRerollAtOne = IXDR_GET_BOOL(buf);
			objp->hasFullReroll = IXDR_GET_BOOL(buf);
		}
	 return TRUE;
	}

	 if (!xdr_int (xdrs, &objp->numOfRolls))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->threshold))
		 return FALSE;
	 if (!xdr_bool (xdrs, &objp->hasRerollAtOne))
		 return FALSE;
	 if (!xdr_bool (xdrs, &objp->hasFullReroll))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_outputData (XDR *xdrs, outputData *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->successfull))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->six))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->one))
		 return FALSE;
	return TRUE;
}
